import Head from "next/head";
import Todos from "../component/Todos";

import styles from "../styles/Home.module.css";
import { background } from "@chakra-ui/react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Todo app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Todos />
      </main>
    </div>
  );
}
